name: email-ai-dev
services:
  db-dev:
    image: postgres
    restart: always
    container_name: email-ai-dev
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-emailai_dev}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    volumes:
      - database-data-dev:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT:-5433}:5432
    networks:
      - email-ai-dev-network

  redis-dev:
    image: redis
    container_name: email-ai-redis-dev
    ports:
      - ${REDIS_PORT:-6381}:6379
    volumes:
      - redis-data-dev:/data
    networks:
      - email-ai-dev-network

  serverless-redis-http-dev:
    container_name: email-ai-redis-http-dev
    ports:
      - "${REDIS_HTTP_PORT:-8080}:80"
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: ${UPSTASH_REDIS_TOKEN:-dev_token}
      SRH_CONNECTION_STRING: "redis://redis-dev:6379"
    networks:
      - email-ai-dev-network

volumes:
  database-data-dev:
  redis-data-dev:

networks:
  email-ai-dev-network:
